export const dummyDataNews = [
    {id: 0, date_created: '03/28/2023', title: 'Tin tức 1', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung đây là nội dung đây là nội dung đây đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung'}, 
    {id: 1, date_created: '03/28/2023', title: 'Tin tức 2', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 2, date_created: '03/28/2023', title: 'Tin tức 3', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 3, date_created: '03/28/2023', title: 'Tin tức 4', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 4, date_created: '03/28/2023', title: 'Tin tức 5', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 5, date_created: '03/28/2023', title: 'Tin tức 6', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 6, date_created: '03/28/2023', title: 'Tin tức 7', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 7, date_created: '03/28/2023', title: 'Tin tức 8', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 8, date_created: '03/28/2023', title: 'Tin tức 1', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung đây là nội dung đây là nội dung đây đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung'}, 
    {id: 9, date_created: '03/28/2023', title: 'Tin tức 2', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 10, date_created: '03/28/2023', title: 'Tin tức 3', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 11, date_created: '03/28/2023', title: 'Tin tức 4', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 12, date_created: '03/28/2023', title: 'Tin tức 5', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 13, date_created: '03/28/2023', title: 'Tin tức 6', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 14, date_created: '03/28/2023', title: 'Tin tức 7', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 15, date_created: '03/28/2023', title: 'Tin tức 8', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 16, date_created: '03/28/2023', title: 'Tin tức 1', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung đây là nội dung đây là nội dung đây đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung'}, 
    {id: 17, date_created: '03/28/2023', title: 'Tin tức 2', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 18, date_created: '03/28/2023', title: 'Tin tức 3', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 19, date_created: '03/28/2023', title: 'Tin tức 4', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 20, date_created: '03/28/2023', title: 'Tin tức 5', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 21, date_created: '03/28/2023', title: 'Tin tức 6', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 22, date_created: '03/28/2023', title: 'Tin tức 7', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 23, date_created: '03/28/2023', title: 'Tin tức 8', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
];

export const dummyDataUsers = [
    {id: 0, name: 'Admin 1', gmail: 'admin@gmail.com', password: '123456', status: 'Hoạt động', isAdmin: true},
    {id: 1, name: 'User 2', gmail: 'user2@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 2, name: 'User 3', gmail: 'user3@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 3, name: 'User 4', gmail: 'user4@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 4, name: 'User 5', gmail: 'user5@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 5, name: 'User 6', gmail: 'user6@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 6, name: 'User 7', gmail: 'user7@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 7, name: 'User 8', gmail: 'user8@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 8, name: 'User 9', gmail: 'user9@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 9, name: 'User 10', gmail: 'user10@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 10, name: 'User 11', gmail: 'user11@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 11, name: 'User 12', gmail: 'user12@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 12, name: 'User 13', gmail: 'user13@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 13, name: 'User 14', gmail: 'user14@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 14, name: 'User 15', gmail: 'user15@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 15, name: 'User 16', gmail: 'user16@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 16, name: 'User 17', gmail: 'user17@gmail.com', password: '123456', status: 'Hoạt động'},
]

export const quizMockData = [ 
    {
        _id: '0',
        image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg',
        title: 'Đề kiểm tra ngữ văn phần 1',
        content: 'Đây là đề kiểm tra kiến thức học sinh sau những bài học trên lớp',
        questions: [
            { question: 'Câu 1: Họ của thúy kiều là gì  ?', options: [{ content: 'Vương', value: 'a'}, { content: 'Mai', value: 'b'}, { content: 'Ngọc', value: 'c'}, { content: 'Nguyễn', value: 'd'}]},
            { question: 'Câu 2: Bác Hồ có tên khác gì gì ?', options: [{ content: 'Nguyễn Lợi', value: 'a'}, { content: 'Nguyễn Trãi', value: 'b'}, { content: 'Phạm Quốc', value: 'c'}, { content: 'Nguyễn Ái Quốc', value: 'd'}]},
            { question: 'Câu 3: Triều đại quân chủ cuối cùng trong lịch ?', options: [{ content: 'Nhà Hồ', value: 'a'}, { content: 'Nhà Thanh', value: 'b'}, { content: 'Nhà Nguyễn', value: 'c'}, { content: 'Nhà Trần', value: 'd'}]},
            { question: 'Câu 4: Lịch sử đô hộ của Việt Nam ta bao nhiêu năm ?', options: [{ content: '1000', value: 'a'}, { content: '10000', value: 'b'}, { content: '200', value: 'c'}, { content: '10', value: 'd'}]},
            { question: 'Câu 5: Triều Đại Phong Kiến Việt Nam dài nhất trong lịch sử nước ta ?', options: [{ content: 'Lê', value: 'a'}, { content: 'Thanh', value: 'b'}, { content: 'Nguyễn', value: 'c'}, { content: 'Lê Sơ', value: 'd'}]},
            { question: 'Câu 6: Họ của thúy kiều là gì  ?', options: [{ content: 'Vương', value: 'a'}, { content: 'Mai', value: 'b'}, { content: 'Ngọc', value: 'c'}, { content: 'Nguyễn', value: 'd'}]},
            { question: 'Câu 7: Bác Hồ có tên khác gì gì ?', options: [{ content: 'Nguyễn Lợi', value: 'a'}, { content: 'Nguyễn Trãi', value: 'b'}, { content: 'Phạm Quốc', value: 'c'}, { content: 'Nguyễn Ái Quốc', value: 'd'}]},
            { question: 'Câu 8: Triều đại quân chủ cuối cùng trong lịch ?', options: [{ content: 'Nhà Hồ', value: 'a'}, { content: 'Nhà Thanh', value: 'b'}, { content: 'Nhà Nguyễn', value: 'c'}, { content: 'Nhà Trần', value: 'd'}]},
            { question: 'Câu 9: Lịch sử đô hộ của Việt Nam ta bao nhiêu năm ?', options: [{ content: '1000', value: 'a'}, { content: '10000', value: 'b'}, { content: '200', value: 'c'}, { content: '10', value: 'd'}]},
            { question: 'Câu 10: Triều Đại Phong Kiến Việt Nam dài nhất trong lịch sử nước ta ?', options: [{ content: 'Lê', value: 'a'}, { content: 'Thanh', value: 'b'}, { content: 'Nguyễn', value: 'c'}, { content: 'Lê Sơ', value: 'd'}]},
        ],
        results: ['a', 'd', 'c', 'a', 'd','a', 'd', 'c', 'a', 'd'],
        testTime: 5,
    },
    {
        _id: '1',
        image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg',
        title: 'Đề kiểm tra toán phần 1',
        content: 'Đây là đề kiểm tra kiến thức học sinh sau những bài học trên lớp',
        questions: [
            { question: 'Câu 1: x + x^2 + 9 với X = 2 thì ra bao nhiêu ?', options: [{ content: '15', value: 'a'}, { content: '12', value: 'b'}, { content: '14', value: 'c'}, { content: '16', value: 'd'}]},
            { question: 'Câu 2: 1+1 = ?', options: [{ content: '33', value: 'a'}, { content: '1', value: 'b'}, { content: '100', value: 'c'}, { content: '4', value: 'd'}]},
            { question: 'Câu 3: Có bao nhiêu hằng đẳng thức đáng nhớ ?', options: [{ content: '5', value: 'a'}, { content: '6', value: 'b'}, { content: '7', value: 'c'}, { content: '8', value: 'd'}]},
            { question: 'Câu 4: Có bao nhiêu phép tính cơ bản được sử dụng ?', options: [{ content: '2', value: 'a'}, { content: '4', value: 'b'}, { content: '3', value: 'c'}, { content: '5', value: 'd'}]},
            { question: 'Câu 5: Tam giác cao bao nhiêu gốc vuông ?', options: [{ content: '1', value: 'a'}, { content: '0', value: 'b'}, { content: '2', value: 'c'}, { content: '3', value: 'd'}]},
            { question: 'Câu 6: x + x^2 + 9 với X = 2 thì ra bao nhiêu ?', options: [{ content: '15', value: 'a'}, { content: '12', value: 'b'}, { content: '14', value: 'c'}, { content: '16', value: 'd'}]},
            { question: 'Câu 7: 1+1 = ?', options: [{ content: '33', value: 'a'}, { content: '1', value: 'b'}, { content: '100', value: 'c'}, { content: '4', value: 'd'}]},
            { question: 'Câu 8: Có bao nhiêu hằng đẳng thức đáng nhớ ?', options: [{ content: '5', value: 'a'}, { content: '6', value: 'b'}, { content: '7', value: 'c'}, { content: '8', value: 'd'}]},
            { question: 'Câu 9: Có bao nhiêu phép tính cơ bản được sử dụng ?', options: [{ content: '2', value: 'a'}, { content: '4', value: 'b'}, { content: '3', value: 'c'}, { content: '5', value: 'd'}]},
            { question: 'Câu 10: Tam giác cao bao nhiêu gốc vuông ?', options: [{ content: '1', value: 'a'}, { content: '0', value: 'b'}, { content: '2', value: 'c'}, { content: '3', value: 'd'}]},
        ],
        results: ['a', 'b', 'c', 'b', 'b','a', 'b', 'c', 'b', 'b'],
        testTime: 5,
    },
    {
        _id: '2',
        image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg',
        title: 'Đề kiểm tra toán phần 2',
        content: 'Đây là đề kiểm tra kiến thức học sinh sau những bài học trên lớp',
        questions: [
            { question: 'Câu 1: Hình vuông có bao nhiêu cạnh ?', options: [{ content: '77', value: 'a'}, { content: '12', value: 'b'}, { content: '7', value: 'c'}, { content: '4', value: 'd'}]},
            { question: 'Câu 2: Số nào lớn nhất ?', options: [{ content: 'Không có số cụ thể', value: 'a'}, { content: '89', value: 'b'}, { content: '9', value: 'c'}, { content: '12', value: 'd'}]},
            { question: 'Câu 3: Có bao nhiêu cách để xếp 4 học sinh trọng 1 hàng ?', options: [{ content: '24', value: 'a'}, { content: '40', value: 'b'}, { content: '22', value: 'c'}, { content: '23', value: 'd'}]},
            { question: 'Câu 4: Công thức tính diện tích hình vuông ?', options: [{ content: 'a*b', value: 'a'}, { content: 'a/a', value: 'b'}, { content: 'a + a', value: 'c'}, { content: 'a*a', value: 'd'}]},
            { question: 'Câu 5: Tính xác xuất ra xúc xắc có số điểm là 6 ?', options: [{ content: '6', value: 'a'}, { content: '1/3', value: 'b'}, { content: '1/2', value: 'c'}, { content: '1/6', value: 'd'}]},
            { question: 'Câu 6: Hình vuông có bao nhiêu cạnh ?', options: [{ content: '77', value: 'a'}, { content: '12', value: 'b'}, { content: '7', value: 'c'}, { content: '4', value: 'd'}]},
            { question: 'Câu 7: Số nào lớn nhất ?', options: [{ content: 'Không có số cụ thể', value: 'a'}, { content: '89', value: 'b'}, { content: '9', value: 'c'}, { content: '12', value: 'd'}]},
            { question: 'Câu 8: Có bao nhiêu cách để xếp 4 học sinh trọng 1 hàng ?', options: [{ content: '24', value: 'a'}, { content: '40', value: 'b'}, { content: '22', value: 'c'}, { content: '23', value: 'd'}]},
            { question: 'Câu 9: Công thức tính diện tích hình vuông ?', options: [{ content: 'a*b', value: 'a'}, { content: 'a/a', value: 'b'}, { content: 'a + a', value: 'c'}, { content: 'a*a', value: 'd'}]},
            { question: 'Câu 10: Tính xác xuất ra xúc xắc có số điểm là 6 ?', options: [{ content: '6', value: 'a'}, { content: '1/3', value: 'b'}, { content: '1/2', value: 'c'}, { content: '1/6', value: 'd'}]},
        ],
        results: ['d', 'a', 'a', 'd', 'd','d', 'a', 'a', 'd', 'd'],
        testTime: 5,
    },
];